# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:12.0
    environment:
      POSTGRES_DB: 'titanic_db'
      POSTGRES_USER: 'titanic'
      POSTGRES_PASSWORD: '/V9A_c?SmJ<]4DRE'
    volumes:
      - ./titanic-postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./titanic-postgres/titanic.csv:/docker-entrypoint-initdb.d/titanic.csv
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  titanicbackend:
    build: ./titanic
#    image: titanic:latest
    environment:
      POSTGRES_USER: 'titanic'
      POSTGRES_PASSWORD: '/V9A_c?SmJ<]4DRE'
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: 'titanic_db'
    ports:
      - 5000:5000
    depends_on:
      - db
